null = None

data = {
    "count": 40,
    "next": "http://new-api.carting.uz/dispatchers/loads/search/?page=2",
    "previous": null,
    "results": [
        {
            "receiver_phone_number": "+998991234567",
            "product_count": 22.0,
            "date_delivery": "2020-01-01T00:23:00+05:00",
            "product_name": "qqqqqqqqqqqqqqqq",
            "product_info": "asdasdasd",
            "product_type": "m",
            "from_location": ["Pop", "Chust"],
            "to_location": ["Angren"],
            "address": "asdfasdf",
            "status": "active",
            "product_image": "http://new-api.carting.uz/media/load_images/b8bd9712-6833-47a3-9388-0eb14e188266.jpg",
            "id": 146,
            "client": {
                "first_name": null,
                "last_name": null,
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998996685214",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 263,
                },
            },
        },
        {
            "receiver_phone_number": "+998991234567",
            "product_count": 11.0,
            "date_delivery": "2020-01-01T00:23:00+05:00",
            "product_name": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "product_info": "qqqqqqqqqqqqq",
            "product_type": "dona",
            "from_location": ["Pop", "Chust", "Namangan shahar"],
            "to_location": ["Angren"],
            "address": "asdfasdfsadf",
            "status": "active",
            "product_image": "http://new-api.carting.uz/media/load_images/56e68fb6-7361-4b31-85f9-f0941302344b.jpg",
            "id": 145,
            "client": {
                "first_name": null,
                "last_name": null,
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998996685214",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 263,
                },
            },
        },
        {
            "receiver_phone_number": "+998991234567",
            "product_count": 222.0,
            "date_delivery": "2024-01-01T00:23:00+05:00",
            "product_name": "qweqweqw",
            "product_info": "asdasdasd",
            "product_type": "m",
            "from_location": ["Pop"],
            "to_location": ["Angren"],
            "address": "asdasdasd",
            "status": "active",
            "product_image": "http://new-api.carting.uz/media/load_images/188d7fd3-dfd2-4577-bb80-fab0920959a0.jpg",
            "id": 144,
            "client": {
                "first_name": null,
                "last_name": null,
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998996685214",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 263,
                },
            },
        },
        {
            "receiver_phone_number": "+998956565659",
            "product_count": 302.0,
            "date_delivery": "2024-04-28T18:25:00+05:00",
            "product_name": "nimadir",
            "product_info": "info",
            "product_type": "dona",
            "from_location": ["Angren"],
            "to_location": ["Angren"],
            "address": "adress",
            "status": "active",
            "product_image": null,
            "id": 143,
            "client": {
                "first_name": "Tester",
                "last_name": "Testerovich",
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998936717139",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 187,
                },
            },
        },
        {
            "receiver_phone_number": "+998912528585",
            "product_count": 19.0,
            "date_delivery": "2024-05-05T19:08:00+05:00",
            "product_name": "zysvzeyxveyxvwusve",
            "product_info": "uwhzwishwushw",
            "product_type": "m",
            "from_location": ["Angren"],
            "to_location": ["Angren"],
            "address": "uwbsuwsbudv",
            "status": "active",
            "product_image": "http://new-api.carting.uz/media/load_images/6babf034-aab1-427f-a4b2-bd7e823fe273.jpg",
            "id": 142,
            "client": {
                "first_name": "aaaaaaa",
                "last_name": "cyuc",
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998935285858",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 255,
                },
            },
        },
        {
            "receiver_phone_number": "+998915648734",
            "product_count": 38.0,
            "date_delivery": "2024-05-08T17:05:00+05:00",
            "product_name": "gdudhdudvddi",
            "product_info": "gdgdhdjdjd",
            "product_type": "kb",
            "from_location": ["Namangan shahar"],
            "to_location": ["Chust"],
            "address": "gejddbdj",
            "status": "active",
            "product_image": "http://new-api.carting.uz/media/load_images/0d8ee28f-fcc1-4ee5-8e0d-f01fdb5b4206.jpg",
            "id": 141,
            "client": {
                "first_name": "aaaaaaa",
                "last_name": "cyuc",
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998935285858",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 255,
                },
            },
        },
        {
            "receiver_phone_number": "+998946253878",
            "product_count": 3.0,
            "date_delivery": "2024-05-05T16:55:00+05:00",
            "product_name": "hchfugugu",
            "product_info": "ufjgjgjg",
            "product_type": "m",
            "from_location": ["Angren"],
            "to_location": ["Chust"],
            "address": "ufutlyoy",
            "status": "active",
            "product_image": "http://new-api.carting.uz/media/load_images/4f01c442-2034-40c4-9945-f0441ecc95c2.jpg",
            "id": 140,
            "client": {
                "first_name": "aaaaaaa",
                "last_name": "cyuc",
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998935285858",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 255,
                },
            },
        },
        {
            "receiver_phone_number": "+998936522847",
            "product_count": 20.0,
            "date_delivery": "2024-05-04T11:33:00+05:00",
            "product_name": "ghgghh",
            "product_info": "yujhyu",
            "product_type": "m",
            "from_location": ["Pop"],
            "to_location": ["Chust"],
            "address": "hcjfufj",
            "status": "active",
            "product_image": "http://new-api.carting.uz/media/load_images/ec437568-8c79-48e4-b7f3-55fa1b568e11.jpg",
            "id": 139,
            "client": {
                "first_name": "2",
                "last_name": "1",
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998978520321",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 247,
                },
            },
        },
        {
            "receiver_phone_number": "+998932685388",
            "product_count": 41.0,
            "date_delivery": "2024-05-09T10:51:00+05:00",
            "product_name": "jchdydgxhchf",
            "product_info": "ghjfihgg",
            "product_type": "kg",
            "from_location": ["Namangan shahar"],
            "to_location": ["Angren"],
            "address": "gdyfufhfigf",
            "status": "active",
            "product_image": "http://new-api.carting.uz/media/load_images/3e6f9a9a-5f63-46dd-b8e5-17f1916117fe.jpg",
            "id": 138,
            "client": {
                "first_name": "Bahodir",
                "last_name": "Fayzirahmonov",
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998931234567",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 182,
                },
            },
        },
        {
            "receiver_phone_number": "+998935658845",
            "product_count": 500.0,
            "date_delivery": "2024-05-21T16:57:00+05:00",
            "product_name": "salafan",
            "product_info": "parnikka",
            "product_type": "m",
            "from_location": ["Namangan shahar"],
            "to_location": ["Angren"],
            "address": "toshkent",
            "status": "active",
            "product_image": "http://new-api.carting.uz/media/load_images/f933068c-486b-42a1-aba3-25a80b03c4a0.jpg",
            "id": 136,
            "client": {
                "first_name": "Bahodir",
                "last_name": "Fayzirahmonov",
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998931234567",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 182,
                },
            },
        },
        {
            "receiver_phone_number": "+998946787678",
            "product_count": 42.0,
            "date_delivery": "2024-05-31T16:53:00+05:00",
            "product_name": "tuxum",
            "product_info": "kerak ekande",
            "product_type": "dona",
            "from_location": ["Angren"],
            "to_location": ["Angren"],
            "address": "qoshniga",
            "status": "active",
            "product_image": "http://new-api.carting.uz/media/load_images/519b845e-6bef-412a-b16d-8ce39f76d565.jpg",
            "id": 135,
            "client": {
                "first_name": "Bahodir",
                "last_name": "Fayzirahmonov",
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998931234567",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 182,
                },
            },
        },
        {
            "receiver_phone_number": "+998945678787",
            "product_count": 50.0,
            "date_delivery": "2024-05-14T16:51:00+05:00",
            "product_name": "un",
            "product_info": "oliy navli",
            "product_type": "kg",
            "from_location": ["Pop"],
            "to_location": ["Pop"],
            "address": "qoshniga",
            "status": "active",
            "product_image": "http://new-api.carting.uz/media/load_images/c3375249-e0f2-4fd6-984e-e66eb9000803.jpg",
            "id": 134,
            "client": {
                "first_name": "Bahodir",
                "last_name": "Fayzirahmonov",
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998931234567",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 182,
                },
            },
        },
        {
            "receiver_phone_number": "+998941532006",
            "product_count": 9.0,
            "date_delivery": "2024-05-02T00:23:00+05:00",
            "product_name": "9",
            "product_info": "9",
            "product_type": "kg",
            "from_location": ["Angren"],
            "to_location": ["Chust"],
            "address": "9",
            "status": "active",
            "product_image": "http://new-api.carting.uz/media/load_images/97191e13-ac19-4d95-ab1d-fb15ff340cfc.jpg",
            "id": 133,
            "client": {
                "first_name": "Akbarshoh",
                "last_name": "Dadamirzayev",
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998941532007",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 11,
                },
            },
        },
        {
            "receiver_phone_number": "+998945667057",
            "product_count": 29.0,
            "date_delivery": "2024-05-03T15:36:00+05:00",
            "product_name": "non",
            "product_info": "kbzsjbzsizb",
            "product_type": "dona",
            "from_location": ["Namangan shahar"],
            "to_location": ["Pop"],
            "address": "kosgdjdb",
            "status": "active",
            "product_image": "http://new-api.carting.uz/media/load_images/426990ce-5c5a-4fcd-bdde-4e1b2e1ed4a7.jpg",
            "id": 131,
            "client": {
                "first_name": "Bahodir",
                "last_name": "Fayzirahmonov",
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998931234567",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 182,
                },
            },
        },
        {
            "receiver_phone_number": "+998974652313",
            "product_count": 3.0,
            "date_delivery": "2024-05-03T14:30:00+05:00",
            "product_name": "hhskdhdhfj",
            "product_info": "hfnfnfjfkfnf",
            "product_type": "kg",
            "from_location": ["Chust"],
            "to_location": ["Angren"],
            "address": "ko'cha",
            "status": "active",
            "product_image": "http://new-api.carting.uz/media/load_images/5a398a93-94dd-47f7-8ca7-6e3996fa5ce5.jpg",
            "id": 129,
            "client": {
                "first_name": "Bahodir",
                "last_name": "Fayzirahmonov",
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998931234567",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 182,
                },
            },
        },
        {
            "receiver_phone_number": "+998201231231",
            "product_count": 112.0,
            "date_delivery": "2024-05-04T09:23:00+05:00",
            "product_name": "ds",
            "product_info": "sdfsdf",
            "product_type": "kb",
            "from_location": ["Namangan shahar"],
            "to_location": ["Angren"],
            "address": "xczdsv",
            "status": "active",
            "product_image": "http://new-api.carting.uz/media/load_images/d6458a78-b9f6-4388-9b3e-3030fece5db1.jpg",
            "id": 127,
            "client": {
                "first_name": "yoz",
                "last_name": "123123",
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998200000000",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 60,
                },
            },
        },
        {
            "receiver_phone_number": "+998201231231",
            "product_count": 12.0,
            "date_delivery": "2024-05-09T09:19:00+05:00",
            "product_name": "1",
            "product_info": "12",
            "product_type": "kg",
            "from_location": ["Angren"],
            "to_location": ["Chust"],
            "address": "vdsc",
            "status": "active",
            "product_image": "http://new-api.carting.uz/media/load_images/2bcb262e-02e5-4d6c-b828-296ff35f93a4.jpg",
            "id": 126,
            "client": {
                "first_name": "yoz",
                "last_name": "123123",
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998200000000",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 60,
                },
            },
        },
        {
            "receiver_phone_number": "+998201231231",
            "product_count": 123.0,
            "date_delivery": "2024-05-03T08:58:00+05:00",
            "product_name": "123",
            "product_info": "123",
            "product_type": "kg",
            "from_location": ["Angren"],
            "to_location": ["Pop"],
            "address": "xcz",
            "status": "active",
            "product_image": null,
            "id": 125,
            "client": {
                "first_name": "yoz",
                "last_name": "123123",
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998200000000",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 60,
                },
            },
        },
        {
            "receiver_phone_number": "+998202132132",
            "product_count": 123.0,
            "date_delivery": "2024-05-05T08:52:00+05:00",
            "product_name": "dscx",
            "product_info": "sdc",
            "product_type": "m",
            "from_location": ["Angren"],
            "to_location": ["Chust"],
            "address": "dsc",
            "status": "active",
            "product_image": null,
            "id": 124,
            "client": {
                "first_name": "yoz",
                "last_name": "123123",
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998200000000",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 60,
                },
            },
        },
        {
            "receiver_phone_number": "+998200000000",
            "product_count": 12.0,
            "date_delivery": "2024-05-03T08:46:00+05:00",
            "product_name": "test",
            "product_info": "test",
            "product_type": "kb",
            "from_location": ["Angren"],
            "to_location": ["Namangan shahar"],
            "address": "test",
            "status": "active",
            "product_image": null,
            "id": 123,
            "client": {
                "first_name": "yoz",
                "last_name": "123123",
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998200000000",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 60,
                },
            },
        },
        {
            "receiver_phone_number": "+998202132131",
            "product_count": 12.0,
            "date_delivery": "2024-05-03T08:45:00+05:00",
            "product_name": "qwd",
            "product_info": "asd",
            "product_type": "kb",
            "from_location": ["Pop"],
            "to_location": ["Angren"],
            "address": "asd",
            "status": "active",
            "product_image": null,
            "id": 122,
            "client": {
                "first_name": "yoz",
                "last_name": "123123",
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998200000000",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 60,
                },
            },
        },
        {
            "receiver_phone_number": "+998940055565",
            "product_count": 10.0,
            "date_delivery": "2024-05-02T19:47:00+05:00",
            "product_name": "korobkada televizor",
            "product_info": "sdafasdfasdf",
            "product_type": "dona",
            "from_location": ["Angren"],
            "to_location": ["Angren"],
            "address": "led jghghj",
            "status": "active",
            "product_image": "http://new-api.carting.uz/media/load_images/efa27874-ce99-4039-8379-b4a0a2305bf8.jpg",
            "id": 118,
            "client": {
                "first_name": "Abdusamad",
                "last_name": "Abdullaxanov",
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998935698858",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 240,
                },
            },
        },
        {
            "receiver_phone_number": "+998998999750",
            "product_count": 657.0,
            "date_delivery": "2024-05-30T05:26:00+05:00",
            "product_name": "doyyossyldhl",
            "product_info": "ludlulud",
            "product_type": "kg",
            "from_location": ["Angren"],
            "to_location": ["Chust"],
            "address": "nfskydyldlhdlhdouroydlhxlhdlu",
            "status": "active",
            "product_image": "http://new-api.carting.uz/media/load_images/41abcdce-30fe-45ef-97fc-e54ef0735d68.jpg",
            "id": 114,
            "client": {
                "first_name": "Husniddin",
                "last_name": "Komilov",
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998999750656",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 239,
                },
            },
        },
        {
            "receiver_phone_number": "+998201231231",
            "product_count": 21.0,
            "date_delivery": "2024-05-07T18:16:00+05:00",
            "product_name": "123",
            "product_info": "123",
            "product_type": "kb",
            "from_location": ["Angren"],
            "to_location": ["Pop"],
            "address": "213",
            "status": "active",
            "product_image": null,
            "id": 113,
            "client": {
                "first_name": "yoz",
                "last_name": "123123",
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998200000000",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 60,
                },
            },
        },
        {
            "receiver_phone_number": "+998999999999",
            "product_count": 11.0,
            "date_delivery": "2024-05-05T18:41:00+05:00",
            "product_name": "asal",
            "product_info": "asal_shodiyeva.activate()",
            "product_type": "dona",
            "from_location": ["Angren"],
            "to_location": ["Angren"],
            "address": "assssssssssssssssssss",
            "status": "active",
            "product_image": "http://new-api.carting.uz/media/load_images/e7ff518e-a037-40c8-8f76-e6e2002cbfa6.jpg",
            "id": 111,
            "client": {
                "first_name": "Abdusamad",
                "last_name": "Abdullaxanov",
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998935698858",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 240,
                },
            },
        },
        {
            "receiver_phone_number": "+998905555555",
            "product_count": 10.0,
            "date_delivery": "2024-05-01T00:46:00+05:00",
            "product_name": "Olcha",
            "product_info": "ajoyib",
            "product_type": "kg",
            "from_location": ["Namangan shahar"],
            "to_location": ["Angren"],
            "address": "nima ishingiz bor mani qayda yashashimi so'rab",
            "status": "active",
            "product_image": "http://new-api.carting.uz/media/load_images/6ebbfb63-7abf-4047-97b0-99c18b36ac2a.jpg",
            "id": 109,
            "client": {
                "first_name": "Ismoilbek",
                "last_name": "Abdumajidov",
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998994776518",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 4,
                },
            },
        },
        {
            "receiver_phone_number": "+998917577139",
            "product_count": 5.0,
            "date_delivery": "2024-05-02T09:13:00+05:00",
            "product_name": "noutbuk",
            "product_info": "oka tezro obkeling",
            "product_type": "dona",
            "from_location": ["Angren"],
            "to_location": ["Namangan shahar"],
            "address": "namangan shahar biror joy",
            "status": "active",
            "product_image": "http://new-api.carting.uz/media/path/to/img.png",
            "id": 100,
            "client": {
                "first_name": "Bahodir",
                "last_name": "Fayzirahmonov",
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998931234567",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 182,
                },
            },
        },
        {
            "receiver_phone_number": "+998200000000",
            "product_count": 123.0,
            "date_delivery": "2024-05-02T09:27:00+05:00",
            "product_name": "fdsc",
            "product_info": "dsc",
            "product_type": "kg",
            "from_location": ["Angren"],
            "to_location": ["Pop"],
            "address": "vcs",
            "status": "active",
            "product_image": "http://new-api.carting.uz/media/path/to/img.png",
            "id": 99,
            "client": {
                "first_name": "yoz",
                "last_name": "123123",
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998200000000",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 60,
                },
            },
        },
        {
            "receiver_phone_number": "+998201231231",
            "product_count": 1.0,
            "date_delivery": "2024-04-30T00:23:00+05:00",
            "product_name": "wdfscx",
            "product_info": "ewdsfrwefdscxz",
            "product_type": "kg",
            "from_location": ["Chust"],
            "to_location": ["Angren"],
            "address": "fvdklmsvmnds j fjiwe gfik gejewgf",
            "status": "active",
            "product_image": "http://new-api.carting.uz/media/path/to/img.png",
            "id": 98,
            "client": {
                "first_name": "yoz",
                "last_name": "123123",
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998200000000",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 60,
                },
            },
        },
        {
            "receiver_phone_number": "+998943557684",
            "product_count": 3.0,
            "date_delivery": "2024-04-30T17:48:00+05:00",
            "product_name": "koptok",
            "product_info": "matchga olib borish kere",
            "product_type": "kb",
            "from_location": ["Pop"],
            "to_location": ["Angren"],
            "address": "namangan",
            "status": "active",
            "product_image": "http://new-api.carting.uz/media/path/to/img.png",
            "id": 97,
            "client": {
                "first_name": "Bahodir",
                "last_name": "Fayzirahmonov",
                "obj_status": "available",
                "user": {
                    "phonenumber": "+998931234567",
                    "user_type": "client",
                    "first_name": null,
                    "last_name": null,
                    "id": 182,
                },
            },
        },
    ],
}

print(len(data["results"]))